# Generated by Django 5.2.7 on 2025-12-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhealth', '0002_customuser_password_user_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='off_days',
            field=models.CharField(default='Сб, Вс', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='working_hours',
            field=models.CharField(default='10:00 - 17:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
