# Generated by Django 5.2.7 on 2025-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhealth', '0002_customuser_password_user_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('therapist', 'Терапевт'), ('surgeon', 'Хирург'), ('pediatrician', 'Педиатр'), ('cardiologist', 'Кардиолог'), ('neurologist', 'Невролог'), ('dentist', 'Стоматолог'), ('ophthalmologist', 'Офтальмолог'), ('dermatologist', 'Дерматолог'), ('psychiatrist', 'Психиатр'), ('other', 'Другое')], default='other', max_length=50),
        ),
    ]
