# Generated by Django 5.2.7 on 2025-12-26 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhealth', '0003_branch_off_days_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='off_days',
            field=models.CharField(default='Сб, Вс', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='Терапевт', max_length=150),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(default='10:00 - 17:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='medhealth.branch'),
        ),
    ]
