# Generated by Django 6.0 on 2025-12-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhealth', '0004_patient_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='selfTreatmentMethodsTaken',
            field=models.TextField(blank=True, default='', verbose_name='Принятые методы самолечения'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptomsDescribedByPatient',
            field=models.TextField(blank=True, default='', verbose_name='Описанные пациентом симптомы'),
        ),
    ]
