# Generated by Django 5.2.7 on 2025-12-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhealth', '0004_doctor_age_doctor_gender_doctor_off_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors_photos/'),
        ),
    ]
