# Generated by Django 6.0 on 2026-01-24 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('medhealth', '0005_remove_doctor_photo_url_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='off_days',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='working_hours',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='off_days',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symptomsDescribedByPatient', models.TextField(blank=True, default='')),
                ('selfTreatmentMethodsTaken', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Завершен'), ('no_show', 'Не пришел'), ('cancelled', 'Отменен')], default='scheduled', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='medhealth.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
                'unique_together': {('doctor', 'date', 'time')},
            },
        ),
    ]
