# Generated by Django 6.0 on 2025-12-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medhealth', '0005_appointment_selftreatmentmethodstaken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Завершен'), ('no_show', 'Не пришел'), ('cancelled', 'Отменен')], default='scheduled', max_length=20, verbose_name='Статус приема'),
        ),
    ]
